### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by free-storage** [Azarattum/Amadeus#2]
How to use it? https://beta.amadeus.ydns.eu/home
I want to connect music from VK. What should be done?

**Comment by Azarattum** [comment]
Hi!

Amadeus is a self-hosted service. It means that you need to spin up your own instance in order to use it.

To do this you need to:
- Clone the repo
- Build the project
```sh
pnpm i && pnpm build
```
- In the `build` directory run `app.cjs`
- Put your auth tokens in `config.json` (readme has links to obtain them)
- Then you can access your instance thought a web ui (like https://beta.amadeus.ydns.eu/home or self-hosted from the `public` directory in `build`) or a Telegram bot (needed to be setup in `config.json`

Please note that web ui is work in progress and might not be stable yet.

**Comment by free-storage** [comment]
@Azarattum Thanks
